name: CI

on:
  push:
    branches:
      - master
      - /-dev|-feature|-fix/

  pull_request:

env:
  JRUBY_OPTS: -J-Xmx896M
  JAVA_OPTS: -Djavax.net.ssl.trustStoreType=JKS

jobs:
  ci:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        java-version: [8, 11, 15]
        ruby-version: [jruby-9.3.7.0, jruby-head]
        task: ['', integration]

      fail-fast: false

    steps:
      - name: Checkout warbler
        uses: actions/checkout@v2
        with:
          path: warbler

      - name: Set up java ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: ${{ matrix.java-version }}

      - name: Set up ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler: 2.3.20

      - name: Install fixed rubygems version
        run: gem update --system 3.3.20

      - name: Install dependencies
        run: bundle _2.3.20_ install --jobs=3 --retry=3
        working-directory: warbler

      - name: Checkout jbundler
        uses: actions/checkout@v2
        with:
          repository: deivid-rodriguez/jbundler
          ref: add_rake_install
          path: jbundler

      - name: Install jbundler
        run: |
          bundle install --jobs=3 --retry=3
          bundle exec rake install
        working-directory: jbundler

      - name: Run tests
        run: bundle exec rake ${{ matrix.TASK }}
        if: matrix.ruby-version !=  'jruby-head'
        working-directory: warbler

      - name: Run tests
        run: bundle exec rake ${{ matrix.TASK }} || exit 0
        if: matrix.ruby-version ==  'jruby-head'
        working-directory: warbler
